name: run

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: build
    runs-on: macos-latest
    env:
      LANG: en_US.UTF-8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install xcpretty
        run: gem install --no-document xcpretty

      # - name: Resolve Swift packages
      #   run: swift package resolve

      - name: Build with xcodebuild
        run: |
          set -o pipefail
          xcodebuild -project Cribbot.xcodeproj \
            -scheme Cribbot \
            -destination 'generic/platform=iOS Simulator' \
            clean build | xcpretty --no-color
        shell: bash
